om_site_settings.site_settings:
  type: config_object
  label: Omedia Site Settings
  mapping:
    archive_length:
      label: 'Archive Length'
      type: number
    website_code:
      label: 'Website Code'
      type: string
    description:
      label: 'Description'
      type: text_format
